# Ansible - Generic PHP develop environment playbook.
#
# This playbook will provision the given hosts performing these main tasks:
#
#   - Update and harden the OS and the network.
#   - Install Apache2, PHP, composer, MySQL client and common develop tools.
#   - Create the given users with allowed SSH access by their given public SSH keys.
#   - Create apache virtual hosts for every given user (<USER>.<HOSTNAME>).
#
# An SSH connection to the remote hosts with sudo access is required.
#
# Apache mod_security is installed but disabled by default due to sometimes being too restrictive
# for a develop environment, even with base rules only activated.
# To enable mod_security, edit the 'roles/common/tasks/apache-harden.yml' file
# and replace 'SecRuleEngine Off' with 'SecRuleEngine On'.
#
# Usage:
#
# 1. Edit the 'hosts' file and fill it with your hosts data.
# 2. Edit the '- hosts:' line, select which ones to provision (available in the hosts file).
#    The given hosts may be a single host, a group or a list of comma-separated hosts/groups.
#    E.g:
#      - hosts: [project1-group]
#      - hosts: project1-dev
# 3. Edit:
#      - ./roles/common/vars/system-groups.yml
#      - ./roles/common/vars/system-users.yml
# 4. Add the users public SSH keys to ./roles/common/public_keys with format <USER>.pub
#      <USER> must coincide with the login name of the user.
#
# 5. Run: ansible-playbook -i hosts dev-env.yml --ask-become-pass --ask-pass
---
- hosts: project1-dev-local

  roles:
    - common
