# Ansible - Generic PHP develop environment playbook.
---
- hosts: project-dev-local

  # The web server not selected will be disabled.
  vars:
    web_server: nginx # apache2 | nginx

  roles:
    - common
