---
- name: Restart ssh.
  service:
    name: ssh
    state: restarted

- name: Restart procps.
  service:
    name: procps
    state: restarted

- name: Restart iptables.
  service:
    name: iptables-persistent
    state: restarted

- name: Restart cron.
  service:
    name: cron
    state: restarted

- name: Reload apache.
  service:
    name: apache
    state: reloaded

- name: Reload nginx.
  service:
    name: nginx
    state: reloaded

- name: Restart web server.
  service:
    name: "{{ web_server }}"
    state: restarted

- name: Restart php-fpm.
  service:
    name: php5.6-fpm
    state: restarted
