---
- name: apt update
  apt: update_cache=yes
  become: yes

- name: install packages
  apt: name={{ item }} state=present
  with_items:
    - curl
    - git
    - vim
    - vim-gnome
    - tree
    - unzip
    - iptables-persistent
    - php5
    - php5-cli
    - php5-dev
    - php5-fpm
    - php5-cgi
    - php5-curl
    - php5-mysql
    - php5-mcrypt
    - php-pear
    - mysql-client
    - apache2
    - libapache2-mod-php5
    - libapache2-mod-security2
    - libapache2-mod-evasive
  notify: restart apache
  become: yes

# For some reason it doesn´t get enabled after installation.
- name: enable php5-mcrypt
  command: php5enmod mcrypt
  become: yes
  notify: restart apache

- name: install symfony
  get_url: url=http://symfony.com/installer dest=/usr/local/bin/symfony mode=0755 force=no
  become: yes
  ignore_errors: yes

- name: install composer
  get_url: url=https://getcomposer.org/composer.phar dest=/usr/local/bin/composer mode=0755 force=no
  become: yes
  ignore_errors: yes
