---
- name: Add ondrej/php repository.
  apt_repository:
    repo: 'ppa:ondrej/php'

- name: Apt update.
  apt:
    update_cache: yes

- name: Install packages.
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - git
    - vim
    - vim-gnome
    - tree
    - unzip
    - iptables-persistent
    - php5.6
    - php5.6-cgi
    - php5.6-cli
    - php5.6-curl
    - php5.6-dev
    - php5.6-fpm
    - php5.6-intl
    - php5.6-ldap
    - php5.6-mysql
    - php5.6-mcrypt
    - php5.6-xml
    - php-pear
    - mysql-client

- name: Install symfony.
  get_url:
    url: "http://symfony.com/installer"
    dest: /usr/local/bin/symfony
    mode: 0755
    force: no
  ignore_errors: yes

- name: Install composer.
  get_url:
    url: "https://getcomposer.org/composer.phar"
    dest: /usr/local/bin/composer
    mode: 0755
    force: no
  ignore_errors: yes

- name: Allow PHP code inside HTML over FPM.
  lineinfile:
    dest: /etc/php/5.6/fpm/pool.d/www.conf
    regexp: '^security.limit_extensions'
    line: 'security.limit_extensions = .php .php3 .php4 .php5 .html'
    state: present
  notify: Restart php-fpm.
