- name: apt update
  apt: update_cache=yes
  become: yes

- name: install packages
  apt: name={{ item }} state=present
  with_items:
    - curl
    - git
    - vim
    - vim-gnome
    - tree
    - unzip
    - iptables-persistent
    - php5
    - php5-cli
    - php5-fpm
    - php5-cgi
    - php5-curl
    - php5-mcrypt
    - apache2
    - libapache2-mod-php5
    - libapache2-mod-security2
    - libapache2-mod-evasive
  notify: restart apache
  become: yes

- name: configure php default_charset to utf8
  lineinfile: dest=/etc/php5/apache2/php.ini regexp='^;\s*default_charset\s*='
    line='default_charset = "UTF-8"'
    state=present
  become: yes

- name: configure php timezone
  lineinfile: dest=/etc/php5/cli/php.ini regexp='^date.timezone\s*='
    line='date.timezone = Europe/Madrid'
    state=present
  become: yes

- name: install symfony
  get_url: url=http://symfony.com/installer dest=/usr/local/bin/symfony mode=0755 force=no
  become: yes
  ignore_errors: yes

- name: install composer
  get_url: url=https://getcomposer.org/composer.phar dest=/usr/local/bin/composer mode=0755 force=no
  become: yes
  ignore_errors: yes
