---
# Vars.
- include_vars: system-groups.yml
- include_vars: system-users.yml
- include_vars: network-security.yml
- include_vars: apache-php-fpm.yml
  when: web_server == 'apache2'
- include_vars: nginx.yml
  when: web_server == 'nginx'

# Tasks.
- include: harden-system.yml
- include: setup-system.yml
- include: install-common.yml
- include: harden-iptables.yml
- include: install-apache.yml
  when: web_server == 'apache2'
- include: setup-apache-vhosts.yml
  when: web_server == 'apache2'
- include: php-dev-config.yml
- include: install-nginx.yml
  when: web_server == 'nginx'
- include: setup-nginx-vhosts.yml
  when: web_server == 'nginx'
