---
# Cli
- name: /etc/php/5.6/cli/php.ini - date.timezone = Europe/Madrid
  lineinfile:
    dest: /etc/php/5.6/cli/php.ini
    regexp: '^date.timezone'
    line: 'date.timezone = Europe/Madrid'
    state: present

- name: /etc/php/5.6/cli/php.ini - display_errors = On
  lineinfile:
    dest: /etc/php/5.6/cli/php.ini
    regexp: '^display_errors'
    line: 'display_errors = On'
    state: present
  notify: Restart web server.

- name: /etc/php/5.6/cli/php.ini - track_errors = On
  lineinfile:
    dest: /etc/php/5.6/cli/php.ini
    regexp: '^track_errors'
    line: 'track_errors = On'
    state: present
  notify: Restart web server.

- name: /etc/php/5.6/cli/php.ini - html_errors = Off
  lineinfile:
    dest: /etc/php/5.6/cli/php.ini
    regexp: '^html_errors'
    line: 'html_errors = Off'
    state: present
  notify: Restart web server.

# Cgi
- name: /etc/php/5.6/cgi/php.ini - date.timezone = Europe/Madrid
  lineinfile:
    dest: /etc/php/5.6/cgi/php.ini
    regexp: '^date.timezone'
    line: 'date.timezone = Europe/Madrid'
    state: present

- name: /etc/php/5.6/cgi/php.ini - display_errors = On
  lineinfile:
    dest: /etc/php/5.6/cgi/php.ini
    regexp: '^display_errors'
    line: 'display_errors = On'
    state: present
  notify: Restart web server.

- name: /etc/php/5.6/cgi/php.ini - track_errors = On
  lineinfile:
    dest: /etc/php/5.6/cgi/php.ini
    regexp: '^track_errors'
    line: 'track_errors = On'
    state: present
  notify: Restart web server.

- name: /etc/php/5.6/cgi/php.ini - html_errors = Off
  lineinfile:
    dest: /etc/php/5.6/cgi/php.ini
    regexp: '^html_errors'
    line: 'html_errors = Off'
    state: present
  notify: Restart web server.

# Fpm
- name: /etc/php/5.6/fpm/php.ini - date.timezone = Europe/Madrid
  lineinfile:
    dest: /etc/php/5.6/fpm/php.ini
    regexp: '^date.timezone'
    line: 'date.timezone = Europe/Madrid'
    state: present

- name: /etc/php/5.6/fpm/php.ini - display_errors = On
  lineinfile:
    dest: /etc/php/5.6/fpm/php.ini
    regexp: '^display_errors'
    line: 'display_errors = On'
    state: present
  notify: Restart web server.

- name: /etc/php/5.6/fpm/php.ini - track_errors = On
  lineinfile:
    dest: /etc/php/5.6/fpm/php.ini
    regexp: '^track_errors'
    line: 'track_errors = On'
    state: present
  notify: Restart web server.

- name: /etc/php/5.6/fpm/php.ini - html_errors = Off
  lineinfile:
    dest: /etc/php/5.6/fpm/php.ini
    regexp: '^html_errors'
    line: 'html_errors = Off'
    state: present
  notify: Restart web server.
