---
- name: Generate locale.
  locale_gen:
    name: "{{ system_locale }}"
    state: present

- name: Set default language and locale.
  template:
    src: default-locale.j2
    dest: /etc/default/locale
    backup: yes

- name: Set timezone.
  # timezone:
  #   name: "{{ system_timezone }}" (will be available in Ansible 2.2.0)
  command: timedatectl set-timezone "{{ system_timezone }}"
  notify: Restart cron.

- name: Create group/s.
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    state: present
  with_items: "{{ system_groups }}"

- name: Remove unwanted user/s
  user:
    name: "{{ item.name }}"
    state: absent
    remove: yes
  with_items: "{{ remove_users }}"
  when: remove_users is defined and remove_users is not none

- name: Remove the unwanted user/s apache sites-available
  file:
    path: /etc/apache2/sites-available/{{ item.name }}.{{ project_url }}.conf
    state: absent
  with_items: "{{ remove_users }}"
  when: remove_users is defined and remove_users is not none

- name: Remove the unwanted user/s apache sites-enabled
  file:
    path: /etc/apache2/sites-enabled/{{ item.name }}.{{ project_url }}.conf
    state: absent
  with_items: "{{ remove_users }}"
  when: remove_users is defined and remove_users is not none

- name: Remove the unwanted user/s nginx sites-available
  file:
    path: /etc/nginx/sites-available/{{ item.name }}.{{ project_url }}.conf
    state: absent
  with_items: "{{ remove_users }}"
  when: remove_users is defined and remove_users is not none

- name: Remove the unwanted user/s nginx sites-enabled
  file:
    path: /etc/nginx/sites-enabled/{{ item.name }}.{{ project_url }}.conf
    state: absent
  with_items: "{{ remove_users }}"
  when: remove_users is defined and remove_users is not none

- name: Create user/s.
  user:
    uid: "{{ item.uid }}"
    name: "{{ item.name }}"
    group: "{{ item.group }}"
    shell: /bin/bash
    state: present
  with_items: "{{ system_users }}"

- name: Authorize user/s public ssh keys.
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ lookup('file', 'roles/common/public_keys/{{ item.name }}.pub') }}"
  with_items: "{{ system_users }}"
  ignore_errors: yes

- name: Create and enable the swap file.
  shell: "fallocate -l {{ ansible_memtotal_mb * 2 }}M /swapfile && chmod 600 /swapfile && mkswap /swapfile && swapon /swapfile"
  args:
    creates: /swapfile

- name: Make the swap file permanent.
  lineinfile:
    dest: /etc/fstab
    regexp: '^/swapfile'
    line: '/swapfile   none    swap    sw    0   0'
    state: present

- name: Improve swappiness.
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: '^vm.swappiness'
    line: 'vm.swappiness: 10'
    state: present

- name: Improve cache pressure.
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: '^vm.vfs_cache_pressure'
    line: 'vm.vfs_cache_pressure :  50'
    state: present
