---
- name: configure locales
  locale_gen: name={{ system_locale }} state=present
  become: yes

- name: set timezone
  # timezone: name={{ system_timezone }} (will be available in Ansible 2.2.0)
  command: timedatectl set-timezone {{ system_timezone }}
  become: yes
  notify: restart cron

- name: create group/s
  group: name={{ item.name }} gid={{ item.gid }} state=present
  with_items: "{{ system_groups }}"
  become: yes

- name: create user/s
  user: uid={{ item.uid }} name={{ item.name }} group={{ item.group }} shell=/bin/bash state=present
  with_items: "{{ system_users }}"
  become: yes

- name: authorize user/s public ssh keys
  authorized_key: user={{ item.name }} key={{ lookup('file', 'roles/common/public_keys/{{ item.name }}.pub') }}
  with_items: "{{ system_users }}"
  ignore_errors: yes
  become: yes

- name: create user/s project directory
  file: path=/home/{{ item.name }}/projects/{{ project_path }}/web owner={{ item.name }}
    group={{ item.group }} state=directory mode=0755
  with_items: "{{ system_users }}"
  become: yes
