---
- name: create virtual hosts
  template: src=virtualhost.j2
    dest=/etc/apache2/sites-available/{{ item.name }}.{{ project_url }}.conf mode=0755
  with_items: "{{ system_users }}"
  become: yes
  notify: restart apache

- name: enable the new virtual hosts
  file: src=/etc/apache2/sites-available/{{ item.name }}.{{ project_url }}.conf
    dest=/etc/apache2/sites-enabled/{{ item.name }}.{{ project_url }}.conf state=link
  with_items: "{{ system_users }}"
  become: yes
  notify: restart apache

# Virtual hosts plan B.
# - name: create links inside apache's document root to the users project/web folders
#   file: src=/home/{{ item.name }}/projects/{{ project_path }}/web dest=/var/www/html/{{ item.name }}
#     state=link
#   with_items: "{{ system_users }}"
#   become: yes
